### PR TITLE
Issue #2794485 - Remove EntityStoreInterface, add EntityStoresInterface

### PR DESCRIPTION
**Pull request by miteshmap**
Removed EntityStoreInterface, moved the relevant methods to OrderInterface, and EntityStoresInterface with the right methods, used by products and promotions.

Ref - https://www.drupal.org/node/2794485

### CODE REVIEW

**Comment by mglaman** [comment]
@miteshmap I don't see modifications to promotion entity?

**Comment by miteshmap** [comment]
@mgalang missed it. I Will work on it.

**Comment by mglaman** [comment]
@miteshmap cool, once rebased w/ change want to remove "needs work" label to "review"

**Comment by bojanz** [comment]
Finished and committed in 923d672ad4848328a2c4374521393e7c960d3d86.

**Pull request closed without merging**
