### PR TITLE
Changed adjustment amount to required only if there is selected any adjustment.

### PR DESCRIPTION
**Pull request by facine**

### CODE REVIEW

**Comment by joshmiller83** [comment]
Without patch:

image

With patch (that applies cleanly):

image

😎

**Comment by joshmiller83** [comment]
Copied over to the following Drupal issue ...

https://www.drupal.org/node/2798757

@facine ... perhaps you could comment there so @bojanz can easily tag you for the drupal.org contribution.

**Comment by mglaman** [comment]
@joshmiller83 they make it easier to assign credit now w/ autocomplete

**Comment by joshmiller83** [comment]
Unfortunately, though, the "states" doesn't seem to actually check for required fields. With patch, a price adjustment with label and no number yields the following fatal PHP error:

The provided value "" is not a numeric value." at /modules/contrib/commerce/modules/price/src/Calculator.php line 196, referer: /admin/commerce/orders/2/edit?destination=/admin/commerce/orders/wishlists

**Comment by mglaman** [comment]
@joshmiller83 so that's a different bug and might be because branch is behind. That shold turn into 0.00

**Comment by bojanz** [comment]
Merging for now, but it's obvious we need to rewrite this widget to remove #states usage (replace it with #ajax)

**Pull request merged**
