### PR TITLE
 Issues #2464347 by bojanz, vasike: Create Cart page - Rebuild the cart view for cart page.

### PR DESCRIPTION
**Pull request by vasike**
Rebuild (put back) the cart view for cart page.

### CODE REVIEW

**Comment by joshuataylor** [comment]
Can you do a rebase so it's easier to review?

**Comment by vasike** [comment]
@joshuataylor is it now better?

**Comment by joshuataylor** [comment]
Awesome, we also need to double check that the config schema etc actually exists, which I'm having problems with at the moment in a related issue.

**Comment by vasike** [comment]
@joshuataylor i'm afraid i do not know what you mean. where do we need this double check, etc?

**Comment by joshuataylor** [comment]
Sorry, I was talking nonsense. I'm looking at this now.

**Comment by bojanz** [comment]
Cart settings need to be per order type, not global.

**Comment by bojanz** [comment]
Committed the finished version in 18e3e521b6f44ed8d60d9f7f4c4d5238215f874c.

**Pull request closed without merging**
