### PR TITLE
Fix travis to use the new autoload workaround in settings.php

### PR DESCRIPTION
**Pull request by joshuataylor**
Also included a couple of tweaks from the redirect module, which might be good to look into it further in future.

Currently tests are failing which I'm looking into now - it's also happening locally.

### CODE REVIEW

**Comment by joshuataylor** [comment]
Actually it seems that travis is still not working for this due to exit codes, please hold 5.

**Comment by joshuataylor** [comment]
Does commerce have PHPUnit tests? These aren't firing.

**Comment by Jbekker** [comment]
No units tests yet but those will come at some point.

**Comment by joshuataylor** [comment]
@Jbekker I've gone ahead and disabled it until it's been added, so once this has been done re-enable it.

**Pull request merged**
