### PR TITLE
Issue 2829043: Redirect to the currencies page after submitting the import form

### PR DESCRIPTION
**Pull request by mitrpaka**

### CODE REVIEW

**Comment by mglaman** [comment]
@mitrpaka in `CurrencyTest::testCurrencyImport` (https://github.com/drupalcommerce/commerce/blob/8.x-2.x/modules/price/tests/src/Functional/CurrencyTest.php#L18) would you mind extending the test to assert we're on the collection route after submitting the form? This way we ensure test coverage.

**Comment by mitrpaka** [comment]
@mglaman Test extended to check that the collection route is the current page after submitting the form. Ready for review.

**Comment by mglaman** [comment]
@mitrpaka looks great, thanks!

**Comment by mglaman** [comment]
@bojanz 👍 for merge? good quick fix

**Comment by mitrpaka** [comment]
Thanks for merging this! 

Drupal issue for this PR seems to be open still (https://www.drupal.org/node/2829043) ... Is that because of missing "#" before issue number?

**Comment by mglaman** [comment]
@mitrpaka ah, yeah. I do this: I copy the git commit command Drupal.org generates (shows on all issues at bottom)

redirect_to_the_currencies_page_after_submitting_the_import_form___2829043____drupal_org

this way when we merge it has the authorship and issue tagging setup

**Pull request merged**
