### PR TITLE
Issue #2754559 - PhpUnit test file-names/classes must have a Test() suffix for auto-discovery

### PR DESCRIPTION
**Pull request by ndf**
https://www.drupal.org/node/2754559

### CODE REVIEW

**Comment by ndf** [comment]
The travis-fail is actually good, because the changed test-class "AddToCartMultiAttributeTest.php" is now actually discovered (and it fails when running).

**Comment by bojanz** [comment]
Great find!

**Comment by ndf** [comment]
All runs ok locally, but Travis seems to have a different issue here.

Time: 37.54 minutes, Memory: 20.00Mb
OK (85 tests, 745 assertions)
  ERROR: No valid tests were specified.
1 fails

**Comment by bojanz** [comment]
@ndf Pushed a fix for that: 11f986978e66fc9abab498ca620552786dc825d4

**Comment by smmccabe** [comment]
Fix to the test looks correct to me, only thing cause a fail is a small code standards whitespace issue now.

**Comment by bojanz** [comment]
Committed in 0d814034503473d906deba2787f74b5ba2f25c59. Fixed the CS violation, removed unneeded comments. Thanks!

**Pull request closed without merging**
