### PR TITLE
Issue #2831895 - AddToCartForm should support multiple instances

### PR DESCRIPTION
**Pull request by steveoliver**
Follow-up to #559 (https://www.drupal.org/node/2827721) - fixes form id to use purchasable entity id instead of static counter which didn't work.
See this issue on d.o: https://www.drupal.org/node/2831895

### CODE REVIEW

**Comment by steveoliver** [comment]
currently submits add to cart forms to purchasable entities' pages. Not ideal as it directs you to another page and cannot continue adding products to cart from the view. :(

**Comment by drugan** [comment]
@steveoliver as for your [comment](https://www.drupal.org/node/2831895#comment-11805221) I'd recommend apply [PR#575](https://patch-diff.githubusercontent.com/raw/drupalcommerce/commerce/pull/575.diff) and see if that works.

**Comment by drugan** [comment]
Would it have sense to remove also $formInstanceId property declaration?

**Comment by drugan** [comment]
@steveoliver  Please, check [this patch](https://www.drupal.org/node/2827721#comment-11812288) if that will work.

**Comment by mglaman** [comment]
This ticket was closed as a duplicate for #582

**Pull request closed without merging**
