### PR TITLE
Basic promotion compat

### PR DESCRIPTION
**Pull request by mglaman**
… promotions present

### CODE REVIEW

**Comment by mglaman** [comment]
This passes locally with PHPUnit but not with `run-tests.sh` locally or travis.

**Comment by mglaman** [comment]
Also needs to be marked required

**Comment by mglaman** [comment]
... a build ran and 2/3 jobs passed on last check (number of adjustments.)

**Comment by mglaman** [comment]
@bojanz the root failures were caused by https://www.drupal.org/node/2863860 I think. I kept the assert but commented out with a todo for that issue.

**Comment by mglaman** [comment]
Let's review but wait to merge until #696 so compat can test sort order.

**Comment by bojanz** [comment]
Looks good.

**Comment by mglaman** [comment]
Since 👍 , I put back failing test for when we rbase once #696 lands

**Pull request merged**
