### PR TITLE
Issue #2734259 by Sagar Ramgade, mglaman: Cart page requires Node mod…

### PR DESCRIPTION
**Pull request by mglaman**
…ule for 'access content' permission

### CODE REVIEW

**Comment by mglaman** [comment]
@bojanz wondering your thoughts on this fix.

**Comment by bojanz** [comment]
Back for 1.x we talked about having our own permission for the cart. Might be a good time to introduce it?

**Comment by mglaman** [comment]
Maybe. But I feel like people would expect users to "just get" access to the cart page. But the same happens for checkout, I suppose. 

I think it makes sense to implement a custom permission then, since we have no dependency on Node, unlike 1.x

**Comment by mglaman** [comment]
@bojanz okay, rebased (was missing commerce_cart port to BrowserTest.) Added new permission to route, updated tests.

**Pull request merged**
