### PR TITLE
Issue #2912996 - Anonymous order payments

### PR DESCRIPTION
**Pull request by bradjones1**
See https://www.drupal.org/node/2912996

### CODE REVIEW

**Comment by bradjones1** [comment]
Ah, coding standards. Will fix.

**Comment by bradjones1** [comment]
@mglaman Any thoughts on why this fails only on PHP7, and on coupon redemption?

**Comment by bojanz** [comment]
@bradjones1
We have a random failure in the coupon redemption test that we're still chasing. I think it's not always visible cause your Travis has different limits than the drupalcommerce/commerce travis.

**Comment by bradjones1** [comment]
@bojanz Ok thanks. Any other thoughts on this PR though?

**Comment by bradjones1** [comment]
Further work at https://github.com/bradjones1/commerce/pull/1

**Comment by bojanz** [comment]
Let's continue on the issue (https://www.drupal.org/node/2912996). I commented about the code needing a reroll for the new PaymentOptions API.

**Pull request closed without merging**
