### PR TITLE
Issue #2757283 by mglaman, cornifex: Re-template the admin and user order views

### PR DESCRIPTION
**Pull request by bojanz**

### CODE REVIEW

**Comment by mglaman** [comment]
@bojanz changing to "full" made it all work.

1___site-install

order_number_1___site-install

**Comment by bojanz** [comment]
Merged in 5fd6298503f0c6930211203144e8667b05a5ac66.

Made the admin page use the "admin" view mode (which falls back to the default view display), fixed bugs in the user template.

**Comment by steveoliver** [comment]
[This change](https://github.com/drupalcommerce/commerce/pull/574/files#diff-c06832ed3372b12ba60dbfe704609d8fR13) made the Payments tab go away from orders - see https://github.com/drupalcommerce/commerce/blob/8.x-2.x/modules/payment/commerce_payment.links.task.yml#L3

**Comment by bojanz** [comment]
@steveoliver 
Another case of missing tests.

**Pull request closed without merging**
