### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pazhyn**
According to Drupal.org Drupal Commerce is in beta and Reported installs are more then 60k.
README.md needs update.

### CODE REVIEW

**Comment by pazhyn** [comment]
Hey, @bojanz can you apply this small pull request with README.md to actualize it with the current state of the project?
Thanks.

**Review by steveoliver — CHANGES_REQUESTED** [review]
I'd change the last two sentences: "But still bugs are expected. You are welcome to report bugs in Issue Tracker." => "Bugs are still expected--please report bugs in the [issue queue](https://www.drupal.org/project/issues/commerce?version=8.x)."

**Comment by pazhyn** [comment]
@steveoliver, done!

**Comment by bojanz** [comment]
Thanks!

**Pull request merged**
