### PR TITLE
Rename variables to $product_type or $product.

### PR DESCRIPTION
**Pull request by joshuataylor**

### CODE REVIEW

**Comment by Jbekker** [comment]
What about our other entities?

**Comment by joshuataylor** [comment]
@Jbekker This is only for variables, not entity names, unless I missed something?

**Comment by Jbekker** [comment]
I meant, there are also $commerce_store_type $commerce_store variables etc. that should be renamed.

**Comment by bojanz** [comment]
I agree with jbekker, let's do that in the next PR.

**Pull request merged**
