### PR TITLE
2925946 - Pass entity type ID to buildFieldDefinitions()

### PR DESCRIPTION
**Pull request by bradjones1**
https://www.drupal.org/project/commerce/issues/2925946

### CODE REVIEW

**Comment by bradjones1** [comment]
@bojanz Not sure exactly how to handle the change to the interface... adding the parameter to the existing interface would break BC for existing traits. Or is this something that would be eligible for a breaking change? Not too excited about the new interface but it seems like it's the only way to both document this and maintain compatibility.

**Comment by bradjones1** [comment]
To answer what is probably a logical question, the use case here is a trait that is the same for both products and product variations, but for the target entity types/bundles for an entity reference field.

**Comment by bradjones1** [comment]
Argh... actually this is totally the wrong approach. Any thoughts?

**Comment by joachim-n** [comment]
I would add a property to the trait plugin base class, and then either set that in the constructor or add a setter.

IIRC, backwards compatibility states that methods may get added to interfaces, and that base classes will add them too. So if you inherit from base classes, your code is fine.

**Comment by bojanz** [comment]
I think we can sidestep this pain by either introducing a setEntityTypeId() and having installTrait() call it, or extending EntityTraitBase to look for an _entity_type in the configuration (which is the pattern we use in TaxTypeBase, PaymentGatewayBase, others) then modifying CommerceBundleEntityBase to pass the entity type ID to createInstance()

**Comment by bradjones1** [comment]
After talking to Bojan in Slack, it looks like this is too edge-case-y and can easily be done on the implementing side without having to change anything in Commerce.

**Pull request closed without merging**
