### PR TITLE
Issue #2575719 Cart test coverage

### PR DESCRIPTION
**Pull request by jbertoen**
Finished the first draft of the cartprovider php unit test. So review it and destroy it with feedback! :smile:

### CODE REVIEW

**Comment by jbertoen** [comment]
Could somebody review this a bit?

**Comment by jbertoen** [comment]
Oops. Sorry, didn't mean to close it haha. Please review.

**Comment by mglaman** [comment]
This is extremely stale, closing. Cart is now added.

**Comment by bojanz** [comment]
The code is still valid, we have no coverage there.

**Comment by bojanz** [comment]
Nevermind, we have the patch in https://www.drupal.org/node/2575719#comment-10988001

**Pull request closed without merging**
