### PR TITLE
#2834416 Move add to cart message to event subscriber - issue

### PR DESCRIPTION
**Pull request by jtolj**

### CODE REVIEW

**Comment by mglaman** [comment]
Fixed the phpcs errors.

**Comment by mglaman** [comment]
@bojanz should we also write up, alongside, a draft documentation page on how to implement compiler pass to unregister this service? or to override it?

**Comment by JTubex** [comment]
Here is a piece of example code on how to override this event subscriber.

Create a new file MyModuleServiceProvider in the src dir of your module (https://www.drupal.org/docs/8/api/services-and-dependency-injection/altering-existing-services-providing-dynamic-services).
```
<?php

namespace Drupal\my_module;

use Drupal\my_module\EventSubscriber\CartEventSubscriber;
use Drupal\Core\DependencyInjection\ContainerBuilder;
use Drupal\Core\DependencyInjection\ServiceProviderBase;
use Symfony\Component\DependencyInjection\Reference;

class MyModuleServiceProvider extends ServiceProviderBase {

  public function alter(ContainerBuilder $container) {
    $container
      ->getDefinition('commerce_cart.cart_subscriber')
      ->setClass(CartEventSubscriber::class)
      ->setArguments([
          new Reference('commerce_cart.cart_provider'),
          new Reference('string_translation'),
          // Add new services when needed.
        ]
      );
  }

}
```
Add a new eventSubscriber e.g. in src/EventSubscriber/CartEventSubscriber.php

```
<?php

namespace Drupal\my_module\EventSubscriber;

use Drupal\commerce_cart\Event\CartEntityAddEvent;
use Drupal\commerce_cart\EventSubscriber\CartEventSubscriber as BaseCartEventSubscriber;

class CartEventSubscriber extends BaseCartEventSubscriber {

  public function displayAddToCartMessage(CartEntityAddEvent $event) {
    // Add your custom code here
  }

}
```

**Comment by bojanz** [comment]
Committed in a3ef38db666a60f765caf3525fd5035399b130b2.

**Pull request closed without merging**
