### PR TITLE
Add install and optional keys to config_devel entries in info.yml files

### PR DESCRIPTION
**Pull request by DuaelFr**
- sort files alphabetically

### CODE REVIEW

**Comment by DuaelFr** [comment]
That failure seems unrelated to the PR.

**Comment by bojanz** [comment]
The build passed, but this needs a rebase now.

**Comment by DuaelFr** [comment]
Done

**Comment by bojanz** [comment]
Rebased again and committed, sorry for the big delay: ac67f7d751fe8f547ca507a51b0bfe12e102ab5c

**Pull request closed without merging**
