### PR TITLE
Issue #2659032 - Add 'cart' cache context

### PR DESCRIPTION
**Pull request by steveoliver**

### CODE REVIEW

**Comment by mglaman** [comment]
@steveoliver I rebased, and added unit test.
@bojanz looks good.

**Comment by steveoliver** [comment]
Reopening, mistook this branch as merged.

**Comment by steveoliver** [comment]
@mglaman this is ready for review.

**Comment by mglaman** [comment]
@bojanz this looks good to me. Safe to merge?

**Pull request merged**
