### PR TITLE
Issue #2640724: Use access handler to prevent edit field access to st…

### PR DESCRIPTION
**Pull request by mglaman**
…ore if entity has been saved

### CODE REVIEW

**Comment by bojanz** [comment]
We should remove the store widget completely, it has no business on the edit page.
Same for uid / email.

**Comment by mglaman** [comment]
Should it just be viewable on the edit, for reference? Make a meta info pane like node and seven?

Should uid, email be added to access handler and then remove hide from form display?

**Comment by mglaman** [comment]
Also.. I think email has a place for edit. What if its an admin created order and the notifications email needs to be updated. I'd want to see what others do for email

**Comment by bojanz** [comment]
It makes sense to show the user / mail in the right sidebar. I guess the store as well? We need to discuss what goes there.

As for the second question, I envisioned a "Reassign order" action that has the same Existing user | New user UI as the add form. So it's editable, just outside of the actual edit screen.

**Comment by mglaman** [comment]
I like that idea. More buttons and specific actions than just fields.

**Comment by mglaman** [comment]
We're going to just manage the form, not access handler.

**Pull request closed without merging**
