### PR TITLE
Add a README.txt

### PR DESCRIPTION
**Pull request by joshmiller83**
:octopus:

### CODE REVIEW

**Comment by rszrama** [comment]
Feel free to propose a more interesting README. :smiley:

**Comment by joshmiller83** [comment]
Woot. On it.

**Comment by bojanz** [comment]
Say something about the fact this is a non-functional dev branch? Link to the issue queue? CG Libraries?

**Comment by joshmiller83** [comment]
Bojan! Ready for a look ... Ryan you might want to see this too...

**Comment by joshmiller83** [comment]
Hey ... realized this pull request was done wrong (need a different branch, need to merge the commits).

**Pull request closed without merging**
