### PR TITLE
Issue #2816237: Create an AdjustmentType plugin for Adjustments

### PR DESCRIPTION
**Pull request by steveoliver**
See https://www.drupal.org/node/2816237

### CODE REVIEW

**Comment by mglaman** [comment]
On phone, but

* Why field definitions in base?
* No need for schema.yml changes, no config entity 
* Should it be a YAML plugin? Having the class doesn't do too much for each adjustment type, does it?

**Comment by steveoliver** [comment]
ah-ha - I wasn't sure exactly how to implement the plugins, but yaml does make sense. And those schema changes made it in accidentally, from when i originally thought we'd have UI and config based types.

**Comment by mglaman** [comment]
Cool! Thanks for tackling this

**Comment by mglaman** [comment]
Looks great. Can we maybe get a test module which provides an adjustment type and add test coverage to widget?

**Pull request merged**
