### PR TITLE
Issue #2804227 Add $order->getBalance()

### PR DESCRIPTION
**Pull request by jackbravo**
This is a rebase of [PR 508](https://github.com/drupalcommerce/commerce/pull/508). Adding a commerce_order_post_update_6() function.

### CODE REVIEW

**Comment by jackbravo** [comment]
I added one more change. Now when we calculate the balance, we consider the payment status. The tests are also updated for this. So I think this is now RTBC, but will wait for someone else to review it.

**Comment by steveoliver** [comment]
Looking good!  Needs a rebase.

**Comment by steveoliver** [comment]
I rebased this branch and put it up for testing at https://github.com/drupalcommerce/commerce/pull/821.  I feel like I may have munged up a commit or two, so let's see..

**Comment by bojanz** [comment]
Continued on the issue https://www.drupal.org/node/2804227

**Pull request closed without merging**
