### PR TITLE
Add price to commerce product testing

### PR DESCRIPTION
**Pull request by joshuataylor**
Once the price is on the product page we can test that the price is correct.

### CODE REVIEW

**Comment by bojanz** [comment]
Merged the other PR, we can now expand this test.

**Comment by joshuataylor** [comment]
Unless I'm slow, is there no way to test the field in the frontend in a better way?

**Comment by bojanz** [comment]
We can create a test for the actual formatter class, but that's out of scope for the product test.

**Comment by bojanz** [comment]
Prices are now on the variation so the test will have to live somewhere else. Closing this for now

**Pull request closed without merging**
