### PR TITLE
Issue #2689911 by andypost: Use a lazy builder in the AddToCartFormatter

### PR DESCRIPTION
**Pull request by andypost**
That's it

### CODE REVIEW

**Comment by andypost** [comment]
Missed https://www.drupal.org/node/2689905

**Comment by bojanz** [comment]
This looks good. However, commerce_cart shouldn't be aware of commerce_product, only the opposite. Since the code in CartLazyBuilders is product specific, it makes more sense for it to live in commerce_product as ProductLazyBuilders (this also allows you to remove the $product_type_id parameter, which is misnamed since it actually gives you the entity type id -> 'commerce_product')

**Comment by andypost** [comment]
Thanx for pointer, I got missed the point of mapping, will update latter

**Comment by andypost** [comment]
Looks ready, should I add a patch to d.o issue or how to proceed?

**Pull request closed without merging**
