### PR TITLE
Issue 2855587: Investigate why DrupalCI fails on checkout based Funct…

### PR DESCRIPTION
**Pull request by drugan**
…ional and FunctionalJavascript tests

BrowserTestBase->drupalGet() takes as the first argument relative path or absolute path or Url object.

But seems that relative path fails in some environments to be resolved to proper url.

### CODE REVIEW

**Comment by mglaman** [comment]
Hm. Does core have to do this? I'll try to run this patch on Drupal.org later and see what happens.

**Comment by drugan** [comment]
I have local server and my dev site's product url looks like this:

http://mysites/acommerce/web/product/1

But with $this->drupalGet($this->product->toUrl()->toString()); it was like this in a test site:

http://mysites/acommerce/web/acommerce/product/1

Now I've run tests localy with $this->drupalGet($this->product->toUrl()) and they all green.

**Comment by mglaman** [comment]
Oh! Our tests aren't using URL generator? Shoot! Updating to toUrl will fix it. We shouldn't be manually constructing at all

**Comment by drugan** [comment]
Every time the Travis checks the PR it gives up on the PHP 7 version. No errors, no warnings or something indicating a trouble. Just this:

> The job exceeded the maximum time limit for jobs, and has been terminated.

Can we to increase the maximum time limit?

**Comment by mglaman** [comment]
We have 50 minutes for each build. We can't bump it.

**Comment by mglaman** [comment]
The URL fixes are 👍  however, it's not fixing the issues after all :(

**Comment by mglaman** [comment]
See https://www.drupal.org/node/2855587#comment-11957449

**Comment by drugan** [comment]
See https://www.drupal.org/node/2855587#comment-11958049

**Comment by bojanz** [comment]
This needs a rebase. The run_tests.sh improvements were merged previously, and CheckoutOrderTest no longer has the access tests.

**Comment by mglaman** [comment]
Let's just close it. It's only reproducible on Drupal.org and the DrupalCI vagrant.

**Pull request closed without merging**
